### ISSUE TITLE
About feature extractions

### ISSUE THREAD

**Issue by Yuuuumie** [Pilhyeon/Learning-Action-Completeness-from-Points#11]
You've mentioned that your work's feature extractions' part was followed https://github.com/piergiaj/pytorch-i3d, but when I tried to apply it to my own datasets, I found that the dimention of layer 'logits.conv3d' is mismatch.

Traceback (most recent call last):
  File "extract_features.py", line 88, in <module>
    run(mode=args.mode, load_model=args.load_model)
  File "extract_features.py", line 51, in run
    i3d.load_state_dict(torch.load(load_model))
  File "/home/pengfang/.conda/envs/mvit/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for InceptionI3d:
        size mismatch for logits.conv3d.weight: copying a param with shape torch.Size([400, 1024, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([54, 1024, 1, 1, 1]).
        size mismatch for logits.conv3d.bias: copying a param with shape torch.Size([400]) from checkpoint, the shape in current model is torch.Size([54]).

 Do I need to finetune the I3D on my datasets? Could you tell me how you apply this code to Thumos14?

**Comment by Yuuuumie** [comment]
What I want to know is why the extracted feature should be related to the output dimension (the number of classes), in the final fully connected layer.
