### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'read' How should I do?

### ISSUE THREAD

**Issue by XD-mu** [Pilhyeon/Learning-Action-Completeness-from-Points#14]
Hello author, I encountered this error when running your code and cannot solve it. What is the reason? The environment and dependent libraries I configured according to your documentation are the same.

Traceback (most recent call last):
  File "./main.py", line 21, in <module>
    config = Config(args)
  File "/home/mcy/miniconda3/envs/python36/lib/python3.6/site-packages/config/__init__.py", line 709, in __init__
    self.load(stream_or_path)
  File "/home/mcy/miniconda3/envs/python36/lib/python3.6/site-packages/config/__init__.py", line 803, in load
    items = p.container()
  File "/home/mcy/miniconda3/envs/python36/lib/python3.6/site-packages/config/parser.py", line 285, in container
    self.advance()
  File "/home/mcy/miniconda3/envs/python36/lib/python3.6/site-packages/config/parser.py", line 130, in advance
    self.token = self.tokenizer.get_token()
  File "/home/mcy/miniconda3/envs/python36/lib/python3.6/site-packages/config/tokens.py", line 997, in get_token
    c = get_char()
  File "/home/mcy/miniconda3/envs/python36/lib/python3.6/site-packages/config/tokens.py", line 802, in get_char
    c = self.stream.read(1)
AttributeError: 'Namespace' object has no attribute 'read'

**Comment by Pilhyeon** [comment]
I am not sure, but it seems like L21 of the "main.py" calls the init function of the external "config" module.

It is an unexpected behavior, because the purpose of the line is to generate a "Config" object of "config.py".

You may check this.

**Comment by XD-mu** [comment]
Thanks to the author for your timely answer. My problem has been solved after updating main.py.
